### ISSUE TITLE
Server freezing for 10-20 seconds

### ISSUE THREAD

**Issue by Nishh** [bergerhealer/BKCommonLib#137]
##### Spigot version: Paper-402 (1.17.1)

Not sure if i need to report this to HolographicDisplays.
Freezing is gone when I removed BKCommonLib. (it was needed for LightCleaner)

<hr>

#### Problem or bug:
Server randomly freezing for some time
Stacktrace: https://pastebin.com/PPyhf32y

#### Steps to reproduce:
Install HolographicDisplays and BKCommonLib, cause some chunk unloading (mine happens without even joining to the server)

**Comment by Nishh** [comment]
Found out there is a lot of holograms created. This might be caused by it.

**Comment by LaurenceBarnes** [comment]
There are known issues with holographic displays causing performance drops at the moment since 3.0. 
Since I cannot reproduce that (I'm using almost all plugins by by bergerkiller and HD together, all updated to their very most recent builds), I'd suggest that you run a spark profiler before reproducing that server stall, stop it after and share the link.
Also it would be helpful if you shared which exact builds you used. Holographic Displays also has a jenkins with some recent fixes for the aforementioned known issues.

**Comment by Nishh** [comment]
Still having problems without BKCommonLib. So its about Holographic Displays and having a lot of displays.

**Comment by LaurenceBarnes** [comment]
make sure to update HD to the latest dev builds from here https://ci.codemc.io/job/filoghost/job/HolographicDisplays/
