### ISSUE TITLE
A few mere questions

### ISSUE THREAD

**Issue by PikaMug** [bergerhealer/BKCommonLib#150]
##### BkCommonLib version:
BKCommonLib-1.19.2-v3-1410
##### Spigot version:
Paper version git-Paper-270 (MC: 1.19.2)

<hr>

1. Where do you enable legacy Material support at startup? I'd like to see how you've done it.
```
[02:12:24 INFO]: [BKCommonLib] Loading BKCommonLib v1.19.2-v3
[02:12:33 ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_19_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
```
2. What is this URL? Doesn't seem to lead anywhere.
https://github.com/bergerhealer/BKCommonLib/blob/05a6ae1c5402bc190df3ebb74261df375e086d4f/src/main/java/com/bergerkiller/bukkit/common/internal/CommonPlugin.java#L659

3. Do me a solid and have a great holiday season? Thanks!

**Comment by bergerkiller** [comment]
1.) BKCommonlib supports MC 1.8 to 1.19.3. Because the data package in bukkit doesnt exist on 1.12.2 and before, it relies on a combination of legacy material classes (which do exist on all versions) and some custom legacy conversion in bkcl to support the new materials like signs, buttons, etc. 

Most of that logic is done here <https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/internal/legacy/IBlockDataToMaterialData.java>

This stuff is by no means final. I'm just waiting for bukkit / spigot / paper devs to decide to actually delete those legacy material classes. When they do, I'll have to write some replacement classes in bkcommonlib. Obviously writing a complete block/item materials api is a lot of effort, something I don't want to spend for no tangible benefit.

2.) Just some joke place

3.) Thanks :)
