### ISSUE TITLE
[FEATURE] Suppot CatServer 1.18.2

### ISSUE THREAD

**Issue by silverfox0000** [bergerhealer/BKCommonLib#151]
##### Spigot version: 1.18.2

<hr>

#### Problem or bug:
Not supporting 1.18.2 CatServer (It makes sense that it would not start)
#### Expected behaviour:
 - Crash xD
#### Steps to reproduce:
- Install CatServer 1.18.2 from jenkins
- Install plugin
- Get an a really big error

EDIT: Forgot add logs link
https://pastebin.com/hZmCFJSu

**Comment by bergerkiller** [comment]
There's sadly still several problems in CatServer 1.18.2's remapper. It's chinese newyear currently so I doubt they have the time at the moment to fix all these issues. I did fix one problem in bkcl itself that caused some trouble.

Fixes some core problems: https://ci.mg-dev.eu/job/BKCommonLib/1455/

The problems that remain are all due to CatServers remapper, and not bkcl. I know because the exact same logic does work on Magma 1.18.2 and ArcLight 1.18.2. You can open an issue ticket there and crosslink with here and stuff.

**Comment by bbayu123** [comment]
Appears that CatServer has already did their work and fixed it. Closing issue.
