### ISSUE TITLE
Add support for Mohist

### ISSUE THREAD

**Issue by Mgazul** [bergerhealer/BKCommonLib#69]
Request to add support for Mohist (a server core similar to the cauldron)
[https://github.com/PFCraft/Mohist](url)

**Comment by weeryan17** [comment]
BKCommonLib works a lot more by interacting with the server via whats know as reflection then using the apis, because of this it's hard to support platforms other then paper and spigot. Their have been several requests to support other platforms before and so far the answer has been no. Ultimately it is up to berger to decide, but just know the answer has so for been no.

**Comment by bergerkiller** [comment]
I will only consider supporting other server architectures if they:
- Are based off of net.minecraft.server source code (can be deobfuscated). This rules out Sponge.
- Has a form of Bukkit API supplied on the server. This (so far) seems to rule out cauldron.

Unless things have changed and cauldron has some form of Bukkit API now, the answer is sadly no.

**Comment by Mgazul** [comment]
okey,thx
