### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by TheDGOfficial** [bergerhealer/BKCommonLib#70]
##### Spigot version: Paper 1.13.2, build 638

<hr>

#### Steps to reproduce:

1. Use Java 11 LTS
2. This warning will show:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.bergerkiller.bukkit.common.utils.LogicUtil (file:/C:/Users/Mustafa/Desktop/Server/plugins/BKCommonLib.jar) to method java.lang.Object.clone()
WARNING: Please consider reporting this to the maintainers of com.bergerkiller.bukkit.common.utils.LogicUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by weeryan17** [comment]
This warning can be safely ignored. It doesn't really mean anything atm.

**Comment by bergerkiller** [comment]
There is no way to disable this warning, it comes from Java itself. It occurs when a reflection is used to access something in the server, which BKCommonLib (obviously) has to do. They want to phase out use of reflection in this way inside Java, and it will be a problem in the (near?) future. The clone() just happens to be the first time reflection is used.

Right now this has no impact. But can leave this issue ticket open for future readers / when java does update and makes such use of reflection impossible.

**Comment by yannicklamprecht** [comment]
The question is if the whole cloning stuff can be avoided? Why you're accessing the clone method? Do you want to disable cloning?

**Comment by bergerkiller** [comment]
This has nothing to do with the cloning method. It is simply the first time reflective access is performed. Theres hundreds to thousands such places. Reflection is used to call clone() on any object type, since at compile time this method is protected and the Cloneable interface is merely a tag, not specifying a clone() method that can be called.

**Comment by TheDGOfficial** [comment]
Looks like i can hide it with the `--add-opens java.base/java.lang=ALL-UNNAMED` command line option, putting before the `-jar`. Maybe it can also be hided/avoided programmatically without the option?

https://stackoverflow.com/questions/46454995/how-to-hide-warning-illegal-reflective-access-in-java-9-without-jvm-argument

**Comment by bergerkiller** [comment]
Quite unlikely, it's a security manager kind of deal. If the jar could disable it that would be a violation in and of itself :)

However, it might be that it only shows warnings when using reflection with JVM types like Object. I can try and see if it can be worked around. Unfortunately I know for sure this isn't possible 100% of the time, because of some [deep-down logic that makes a static final field modifiable](https://github.com/bergerhealer/Mountiplex/blob/master/src/main/java/com/bergerkiller/mountiplex/reflection/util/DisableFinalModifierHelper.java#L40).

**Comment by bergerkiller** [comment]
Ive made some changes so that LogicUtil clone() no longer uses reflection on Object directly, that seems to have quieted down that warning.

**Comment by TheDGOfficial** [comment]
It seems like you also fixed the deep-down logic you mentioned on Java 11/12. Thanks. I will try a new build from Jenkins in a fresh Java 12 and 1.14.4 Paper server. I will close the issue if it's resolved.
