### ISSUE TITLE
Field 'entitiesById' could not be found in class net.minecraft.server.v1_15_R1.WorldServer

### ISSUE THREAD

**Issue by mibby** [bergerhealer/BKCommonLib#89]
##### Spigot version: Purpur dev 486 (PaperSpigot Fork / Spigot 1.15.2)

<hr>

```
[03:55:28] [Server thread/INFO]: [BKCommonLib] Loading BKCommonLib v1.15.2-v2
[03:55:30] [Server thread/WARN]: [REFLECTION] Field 'entitiesById' in class net.minecraft.server.v1_15_R1.WorldServer is of type Int2ObjectLinkedOpenHashMap while we expect type Int2ObjectMap
[03:55:30] [Server thread/WARN]: [REFLECTION] Field 'entitiesById' could not be found in class net.minecraft.server.v1_15_R1.WorldServer
```

**Comment by bergerkiller** [comment]
Bah, did they change this right after I make a 1.15.2-v2 release? Bummer. Should be an easy fix though

**Comment by bergerkiller** [comment]
This change is a big problem, I hope I can add compatibility for it

```
+    //public final Long2ObjectLinkedOpenHashMap<PlayerChunk> updatingChunks = new Long2ObjectLinkedOpenHashMap(); // Tuinity - replace chunk map
+    //public volatile Long2ObjectLinkedOpenHashMap<PlayerChunk> visibleChunks; // Tuinity - replace chunk map
+    public final com.tuinity.tuinity.chunk.QueuedChangesMapLong2Object<PlayerChunk> chunkMap = new com.tuinity.tuinity.chunk.QueuedChangesMapLong2Object<>(8192, 0.7f); // Tuinity - replace chunk map
```

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/BKCommonLib/commit/7b766cd62c71deb92757670d8265c12bc84d5c89 fixes the issue reported here, but not all issues are fixed.

There are no errors, but trains in Traincarts are no longer persistent. When chunks unload and then reload, they all revert back to glitched vanilla minecarts. There is something else they changed Im not accounting for.

I have a hard time debugging purpur because I dont have any source code, all I can read are the patch files. Their build scripts are failing on my end. And thanks to java11 the decompiler I use can't work with the purpur server jar :/

**Comment by mibby** [comment]
:(

@BillyGalbreath

**Comment by BillyGalbreath** [comment]
@spottedleaf

**Comment by bergerkiller** [comment]
@BillyGalbreath https://github.com/pl3xgaming/Purpur/ right?

I git clone'd it and went through the setting up steps, but it failed during the ./purpur up step. Lots of NULL NMS log lines among things, tho this might not be the place to resolve that. It might be better to make an issue ticket on the purpur repo for this.

**Comment by BillyGalbreath** [comment]
> but it failed during the ./purpur up step. Lots of NULL NMS log lines among things
I've seen this before, not sure what causes it, tbh. A quick fix is to `cd` into the Paper submodule and run `./paper patch`. I can't seem to reproduce it, so I'm assuming it's some quirk with Windows/gitbash.

**Comment by bergerkiller** [comment]
Thanks, I had to also fix up $PATH because it couldnt find mvn nor jar (java11, it was probably using java8 or something, or the jre). Ill see how far I can get

**Comment by bergerkiller** [comment]
Thanks for the help, I got it to run locally so I can do some testing. Im creating a diff from spigot 1.15.2 to purpur 1.15.2 and then I'll see what could be to blame for this breakage

**Comment by bergerkiller** [comment]
@BillyGalbreath is there any chance Purpur devs can make the PlayerChunkMap$EntityTracker updateTrackingPlayer method non-final? Right now there is only a way to hook into 'player visible' and 'player no longer visible' method callbacks, but I have my own code to check visibility which is now broken.

**Comment by Spottedleaf** [comment]
The issue here isn't an issue with purpur - it's with tuinity. Purpur "forks" tuinity, not paper.

The fact I modify the field type for `entitiesById` is an error, there's no need for me to do it, it should just be casted to the type I want when using the value. I've put this on my list to fix.


> 
> 
> @BillyGalbreath is there any chance Purpur devs can make the PlayerChunkMap$EntityTracker updateTrackingPlayer method non-final? Right now there is only a way to hook into 'player visible' and 'player no longer visible' method callbacks, but I have my own code to check visibility which is now broken.
> 
> The updatePlayer() method that is also in there doesn't appear to be called anymore, only when the minecart is first spawned. Its useless for when new players spawn.

I don't know what you want to use that method for, if you could explain what you want to use that method for I will see if there's a way around it - else I will look into revising the change.

> 
> 
> This change is a big problem, I hope I can add compatibility for it
> 
> ```
> +    //public final Long2ObjectLinkedOpenHashMap<PlayerChunk> updatingChunks = new Long2ObjectLinkedOpenHashMap(); // Tuinity - replace chunk map
> +    //public volatile Long2ObjectLinkedOpenHashMap<PlayerChunk> visibleChunks; // Tuinity - replace chunk map
> +    public final com.tuinity.tuinity.chunk.QueuedChangesMapLong2Object<PlayerChunk> chunkMap = new com.tuinity.tuinity.chunk.QueuedChangesMapLong2Object<>(8192, 0.7f); // Tuinity - replace chunk map
> ```

What exactly are you using these fields for?

**Comment by bergerkiller** [comment]
@Spottedleaf No need to make changes now, I've worked around it by being more relaxed in my type checking. In a lot of places I match fields and methods exactly so that I'm aware when forks or version changes make changes to them, because sometimes those changes are breaking.

I use that method for this method, which is further implemented by other plugins. isViewable differs slightly from what the server does.

```
    /**
     * Adds or removes a viewer based on viewer distance
     *
     * @param viewer to update
     */
    public final void updateViewer(Player viewer) {
        // If viewer has blindness due to respawning, do not make it visible just yet
        // When blindness runs out, perform an updateViewer again to make this entity visible quickly
        if (!CommonPlugin.getInstance().getPlayerMeta(viewer).respawnBlindnessCheck(this)) {
            return;
        }

```
        // Add or remove the viewer depending on whether this entity is viewable by the viewer
        if (isViewable(viewer)) {
            addViewer(viewer);
        } else {
            removeViewer(viewer);
        }
    }
```

> What exactly are you using these fields for?
The method to get the player chunk is protected, and includes primitive parameters (long). Calling this using reflection causes not only overhead due to visibility, it also boxes and then unboxes the long, resulting in overhead. I'm instead calling .visibleChunks.get(long) in generated code directly to avoid these overheads.

**Comment by bergerkiller** [comment]
I think I can work around this final method with a minor rewrite

**Comment by Spottedleaf** [comment]
> 
> 
> @Spottedleaf No need to make changes now, I've worked around it by being more relaxed in my type checking. In a lot of places I match fields and methods exactly so that I'm aware when forks or version changes make changes to them, because sometimes those changes are breaking.

I'm going to revert the change to entitiesById field anyways, there's more than one plugin it could break.

> I use that method for this method, which is further implemented by other plugins. isViewable differs slightly from what the server does.

Yes I see now, it looks like in order to fix it you would have to write your own tracker logic. I'm going to add methods to Entity which will allow you to set the entity to vanilla tracking (it already exists sort of, but there's some stuff I overlooked) so that really you don't need to change anything.


> The method to get the player chunk is protected, and includes primitive parameters (long). Calling this using reflection causes not only overhead due to visibility, it also boxes and then unboxes the long. I'm instead calling .visibleChunks.get(long) in generated code directly to avoid this

Paper makes PlayerChunk#getVisibleChunk(long) public. I'd recommend sticking to those methods as I will correctly preserve behaviour provided in vanilla.
For example, chunkMap.getVisible(long) is not thread-safe unlike the previous visibleChunks.get(long), however chunkMap.getVisibleAsync(long) is thread-safe. The method PlayerChunkMap#getVisibleChunk will correctly pick which one to use depending on the current thread.

This change can't be reverted. The visible chunk map is a full copy of the updating chunk map, and the visible map is updated by recloning the updating map (to make it thread-safe).
I change the map because that copying causes GC issues, so the only way I can fix the GC issue is by replacing the maps.


This line here
https://github.com/bergerhealer/BKCommonLib/commit/7b766cd62c71deb92757670d8265c12bc84d5c89#diff-07ac04afa07b85b1dbaca963cb160207R62
is a total misuse of the fields. The visibleChunks map needs to be a copy because non-main threads will use this map. 
I read the comment about why this method is used and I still can't see why this is needed, EntityTracker objects aren't stored anywhere in PlayerChunk or the chunkmap.

**Comment by bergerkiller** [comment]
Let me clarify that line for you, as it has absolutely nothing to do with the server itself.

Somewhere in the code I am replacing the entire PlayerChunkMap instance temporarily to prevent the server executing tracking logic while I'm spawning or teleporting an entity. This makes sure no vanilla spawn packets are sent out, since I have a custom network controller set to handle that instead. After this is is done, the player chunk map is restored to the original value.

That line above avoids a memory leak that can be caused if that temporary PlayerChunkMap generated class instance stays around for some reason. For example, there was a bug I fixed that some internal implementation detail in mountiplex caused that instance to stay around forever. Because it stored an at-that-time copy of all loaded chunks, it caused an out of control memory leak.

By setting it to the field value itself, rather than clone(), I make sure that whatever is still holding onto it is not also holding onto a copy of all PlayerChunk instances. I could've set it to null to the same effect, but was worried that this could cause mysterious errors down the line.

Don't worry about it, that code is not used on the actual PlayerChunkMap instance used on the server.

`For example, chunkMap.getVisible(long) is not thread-safe`
I'm not calling into that method from another thread, as I assume no method to be thread-safe anywhere in my code. I'll ccall your public method instead though, that way when you change the backing class it won't break things.

**Comment by bergerkiller** [comment]
This fixes the problem of players not being added as viewer to network controllers. https://github.com/bergerhealer/BKCommonLib/commit/d279b93f6f2cde24025b0b43546a3a7e2993c8da

**Comment by Spottedleaf** [comment]
These commits here are my fixes:
https://github.com/Spottedleaf/Tuinity/compare/e2d2b0f9508c...028c3b18c4ae

world entity map field type change was reverted
Entities can be set to "legacy" tracking via Entity#setLegacyTrackingEntity, which means updatePlayer is called (for each player on the world) each tick instead of the method I introduced

**Comment by bergerkiller** [comment]
Thanks, while I already worked around it, I'll add some code to call that method to make sure any bugs caused by it don't happen in the future.

The issue of entities disappearing appears to be an issue with Paperspigot, not purpur. Very likely some field they added for optimization that I am not updating, causing some weird glitch when saving the chunk.

**Comment by bergerkiller** [comment]
@Spottedleaf not sure if you're in control of that, but the build server is down: https://ci.pl3x.net/job/Purpur/

Thought I could work around it by building myself but one of the dependencies are also hosted there, so that fails too

**Comment by Spottedleaf** [comment]
purpur is a separate thing entirely from tuinity, so no I don't have control of billy's ci

**Comment by bergerkiller** [comment]
I've fixed all remaining issues

https://github.com/bergerhealer/BKCommonLib/commit/65dbb3276e207d7bf2e98060a73e4659b062bd7e
https://github.com/bergerhealer/BKCommonLib/commit/3df64533c0a5c86a4a6e4f74d6e5453b2fc0147f
https://github.com/bergerhealer/BKCommonLib/commit/1e793c3c8a8873ab7228fb5d92b4a65226dd51c0
